const filmes = [
  {
    id: 1,
    nome: "O Exorcista",
    ano: 1974,
    diretor: "William Friedkin",
    categoria: "Terror/Suspense",
    categoriaId: 1,
    nota: 10,
    assistiu: false,
  },
  {
    id: 2,
    nome: "O Sexto Sentido",
    ano: 1999,
    diretor: " M. Night Shyamalan",
    categoria: "Terror/Suspense",
    categoriaId: 1,
    nota: 8,
    assistiu: true,
  },
  {
    id: 3,
    nome: "Psicose",
    ano: 1960,
    diretor: "M. Night Shyamalan",
    categoria: "Terror/Suspense",
    categoriaId: 1,
    nota: 8,
    assistiu: true,
  },
  {
    id: 4,
    nome: "Uncharted",
    ano: 2022,
    diretor: "Ruben Fleischer",
    categoria: "Ação/Aventura",
    categoriaId: 2,
    nota: 6.5,
    assistiu: false,
  },
  {
    id: 5,
    nome: "Todo-Poderoso",
    ano: 2003,
    diretor: "Tom Shadyak",
    categoria: "Comédia",
    categoriaId: 3,
    nota: 9,
    assistiu: true,
  },
  {
    id: 6,
    nome: "Senhor dos Anéis",
    ano: 2002,
    diretor: "Peter Jackson",
    categoria: "Ação/Aventura",
    categoriaId: 2,
    nota: 9,
    assistiu: true,
  },
  {
    id: 7,
    nome: "Curtindo a Vida Adoidado",
    ano: 1986,
    diretor: "John Hughes",
    categoria: "Comédia",
    categoriaId: 3,
    nota: 10,
    assistiu: true,
  },
];

module.exports = filmes;
